### ISSUE TITLE
NPM tarball missing files for 2.0 release

### ISSUE THREAD

**Issue by adamup928** [cronitorio/cronitor-js#11]
Installing with NPM results in `cronitor.js` as the only file inside the `lib` folder.

I thought maybe something was up with my NPM cache, so I checked with [list-npm-contents](https://github.com/natecavanaugh/list-npm-contents#readme), and it appears there are missing files when compared with the repo.

Thanks!

**Comment by aflanagan** [comment]
Thanks for reporting this @adamup928! I'm still new to publishing npm packages and the `files` array was left in the package.json from the 1.x series. This tells npm specifically which files to include in the tarball. I've published 2.0.1 to fix this and will mark 2.0.0 as deprecated on npm.
