### ISSUE TITLE
request: typescript types

### ISSUE THREAD

**Issue by puckey** [cronitorio/cronitor-js#17]
Are there any plans for typescript types for this library?

**Comment by aflanagan** [comment]
@puckey we'd love to support typescript types! Unfortunately, it's not on our internal roadmap right now. If you're interested in working on this, please reach out to support and we'd be happy to assist!

**Comment by puckey** [comment]
thanks - I ended up writing my own rest wrapper instead. I will be sure to revisit this client if typescript types ever surface - it looks good
