### ISSUE TITLE
node-cron wrapper doesn't work

### ISSUE THREAD

**Issue by samarth-agrawal-86** [cronitorio/cronitor-js#26]
The following line of code should create a monitor in the dashboard and give the job level details but it doesn't work
```js
const express = require("express");
const cronitor = require("cronitor")(process.env.CRONITOR_API_KEY);
const nodeCron = require("node-cron");

app = express();
cronitor.wraps(nodeCron);

cronitor.schedule("EveryMin", "* * * * *", function () {
  console.log("Console Log every min");
});

let port = process.env.PORT;
if (port == null || port == "") {
  port = 3000;
}

app.listen(port, function (req, res) {
  console.log("Server started");
});
```

**Comment by aflanagan** [comment]
Apologies for the slow reply -- If i had to guess, it's that the `CRONITOR_API_KEY` is not being properly passed through. Another customer just configured this, and that was the part they had wrong. Once that was updated, it was working as expected. I've also confirmed the integration tests still work for that library. 

Please re-open/comment if you're still running into issues!
